name: "notes"
version: "1.0.1"
usage: "Render the NOTES.txt helm file without deploying the application"
description: "Render the NOTES.txt helm file without deploying the application"
useTunnel: true
command: "$HELM_PLUGIN_DIR/bin/notes"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh -u"